/**
 * Static country information mapping
 * Contains capitals, ISO codes, and coordinates
 */

export interface CountryInfo {
  capital: string;
  iso2: string;
  iso3: string;
}

export const COUNTRY_INFO: Record<string, CountryInfo> = {
  // Europe
  'albania': { capital: 'Tirana', iso2: 'AL', iso3: 'ALB' },
  'andorra': { capital: 'Andorra la Vella', iso2: 'AD', iso3: 'AND' },
  'austria': { capital: 'Vienna', iso2: 'AT', iso3: 'AUT' },
  'belarus': { capital: 'Minsk', iso2: 'BY', iso3: 'BLR' },
  'belgium': { capital: 'Brussels', iso2: 'BE', iso3: 'BEL' },
  'bosnia and herzegovina': { capital: 'Sarajevo', iso2: 'BA', iso3: 'BIH' },
  'bulgaria': { capital: 'Sofia', iso2: 'BG', iso3: 'BGR' },
  'croatia': { capital: 'Zagreb', iso2: 'HR', iso3: 'HRV' },
  'czech republic': { capital: 'Prague', iso2: 'CZ', iso3: 'CZE' },
  'denmark': { capital: 'Copenhagen', iso2: 'DK', iso3: 'DNK' },
  'estonia': { capital: 'Tallinn', iso2: 'EE', iso3: 'EST' },
  'finland': { capital: 'Helsinki', iso2: 'FI', iso3: 'FIN' },
  'france': { capital: 'Paris', iso2: 'FR', iso3: 'FRA' },
  'germany': { capital: 'Berlin', iso2: 'DE', iso3: 'DEU' },
  'greece': { capital: 'Athens', iso2: 'GR', iso3: 'GRC' },
  'hungary': { capital: 'Budapest', iso2: 'HU', iso3: 'HUN' },
  'iceland': { capital: 'Reykjavik', iso2: 'IS', iso3: 'ISL' },
  'ireland': { capital: 'Dublin', iso2: 'IE', iso3: 'IRL' },
  'italy': { capital: 'Rome', iso2: 'IT', iso3: 'ITA' },
  'latvia': { capital: 'Riga', iso2: 'LV', iso3: 'LVA' },
  'lithuania': { capital: 'Vilnius', iso2: 'LT', iso3: 'LTU' },
  'luxembourg': { capital: 'Luxembourg', iso2: 'LU', iso3: 'LUX' },
  'malta': { capital: 'Valletta', iso2: 'MT', iso3: 'MLT' },
  'moldova': { capital: 'Chisinau', iso2: 'MD', iso3: 'MDA' },
  'monaco': { capital: 'Monaco', iso2: 'MC', iso3: 'MCO' },
  'montenegro': { capital: 'Podgorica', iso2: 'ME', iso3: 'MNE' },
  'netherlands': { capital: 'Amsterdam', iso2: 'NL', iso3: 'NLD' },
  'north macedonia': { capital: 'Skopje', iso2: 'MK', iso3: 'MKD' },
  'norway': { capital: 'Oslo', iso2: 'NO', iso3: 'NOR' },
  'poland': { capital: 'Warsaw', iso2: 'PL', iso3: 'POL' },
  'portugal': { capital: 'Lisbon', iso2: 'PT', iso3: 'PRT' },
  'romania': { capital: 'Bucharest', iso2: 'RO', iso3: 'ROU' },
  'russia': { capital: 'Moscow', iso2: 'RU', iso3: 'RUS' },
  'san marino': { capital: 'San Marino', iso2: 'SM', iso3: 'SMR' },
  'serbia': { capital: 'Belgrade', iso2: 'RS', iso3: 'SRB' },
  'slovakia': { capital: 'Bratislava', iso2: 'SK', iso3: 'SVK' },
  'slovenia': { capital: 'Ljubljana', iso2: 'SI', iso3: 'SVN' },
  'spain': { capital: 'Madrid', iso2: 'ES', iso3: 'ESP' },
  'sweden': { capital: 'Stockholm', iso2: 'SE', iso3: 'SWE' },
  'switzerland': { capital: 'Bern', iso2: 'CH', iso3: 'CHE' },
  'ukraine': { capital: 'Kyiv', iso2: 'UA', iso3: 'UKR' },
  'united kingdom': { capital: 'London', iso2: 'GB', iso3: 'GBR' },
  'vatican city': { capital: 'Vatican City', iso2: 'VA', iso3: 'VAT' },

  // Asia
  'afghanistan': { capital: 'Kabul', iso2: 'AF', iso3: 'AFG' },
  'armenia': { capital: 'Yerevan', iso2: 'AM', iso3: 'ARM' },
  'azerbaijan': { capital: 'Baku', iso2: 'AZ', iso3: 'AZE' },
  'bahrain': { capital: 'Manama', iso2: 'BH', iso3: 'BHR' },
  'bangladesh': { capital: 'Dhaka', iso2: 'BD', iso3: 'BGD' },
  'bhutan': { capital: 'Thimphu', iso2: 'BT', iso3: 'BTN' },
  'brunei': { capital: 'Bandar Seri Begawan', iso2: 'BN', iso3: 'BRN' },
  'cambodia': { capital: 'Phnom Penh', iso2: 'KH', iso3: 'KHM' },
  'china': { capital: 'Beijing', iso2: 'CN', iso3: 'CHN' },
  'india': { capital: 'New Delhi', iso2: 'IN', iso3: 'IND' },
  'indonesia': { capital: 'Jakarta', iso2: 'ID', iso3: 'IDN' },
  'iran': { capital: 'Tehran', iso2: 'IR', iso3: 'IRN' },
  'iraq': { capital: 'Baghdad', iso2: 'IQ', iso3: 'IRQ' },
  'israel': { capital: 'Jerusalem', iso2: 'IL', iso3: 'ISR' },
  'japan': { capital: 'Tokyo', iso2: 'JP', iso3: 'JPN' },
  'jordan': { capital: 'Amman', iso2: 'JO', iso3: 'JOR' },
  'kazakhstan': { capital: 'Astana', iso2: 'KZ', iso3: 'KAZ' },
  'kuwait': { capital: 'Kuwait City', iso2: 'KW', iso3: 'KWT' },
  'kyrgyzstan': { capital: 'Bishkek', iso2: 'KG', iso3: 'KGZ' },
  'laos': { capital: 'Vientiane', iso2: 'LA', iso3: 'LAO' },
  'lebanon': { capital: 'Beirut', iso2: 'LB', iso3: 'LBN' },
  'malaysia': { capital: 'Kuala Lumpur', iso2: 'MY', iso3: 'MYS' },
  'maldives': { capital: 'Malé', iso2: 'MV', iso3: 'MDV' },
  'mongolia': { capital: 'Ulaanbaatar', iso2: 'MN', iso3: 'MNG' },
  'myanmar': { capital: 'Naypyidaw', iso2: 'MM', iso3: 'MMR' },
  'nepal': { capital: 'Kathmandu', iso2: 'NP', iso3: 'NPL' },
  'north korea': { capital: 'Pyongyang', iso2: 'KP', iso3: 'PRK' },
  'oman': { capital: 'Muscat', iso2: 'OM', iso3: 'OMN' },
  'pakistan': { capital: 'Islamabad', iso2: 'PK', iso3: 'PAK' },
  'palestine': { capital: 'Ramallah', iso2: 'PS', iso3: 'PSE' },
  'philippines': { capital: 'Manila', iso2: 'PH', iso3: 'PHL' },
  'qatar': { capital: 'Doha', iso2: 'QA', iso3: 'QAT' },
  'saudi arabia': { capital: 'Riyadh', iso2: 'SA', iso3: 'SAU' },
  'singapore': { capital: 'Singapore', iso2: 'SG', iso3: 'SGP' },
  'south korea': { capital: 'Seoul', iso2: 'KR', iso3: 'KOR' },
  'sri lanka': { capital: 'Colombo', iso2: 'LK', iso3: 'LKA' },
  'syria': { capital: 'Damascus', iso2: 'SY', iso3: 'SYR' },
  'taiwan': { capital: 'Taipei', iso2: 'TW', iso3: 'TWN' },
  'tajikistan': { capital: 'Dushanbe', iso2: 'TJ', iso3: 'TJK' },
  'thailand': { capital: 'Bangkok', iso2: 'TH', iso3: 'THA' },
  'turkey': { capital: 'Ankara', iso2: 'TR', iso3: 'TUR' },
  'turkmenistan': { capital: 'Ashgabat', iso2: 'TM', iso3: 'TKM' },
  'united arab emirates': { capital: 'Abu Dhabi', iso2: 'AE', iso3: 'ARE' },
  'uzbekistan': { capital: 'Tashkent', iso2: 'UZ', iso3: 'UZB' },
  'vietnam': { capital: 'Hanoi', iso2: 'VN', iso3: 'VNM' },
  'yemen': { capital: 'Sanaa', iso2: 'YE', iso3: 'YEM' },

  // Americas
  'argentina': { capital: 'Buenos Aires', iso2: 'AR', iso3: 'ARG' },
  'bolivia': { capital: 'La Paz', iso2: 'BO', iso3: 'BOL' },
  'brazil': { capital: 'Brasília', iso2: 'BR', iso3: 'BRA' },
  'canada': { capital: 'Ottawa', iso2: 'CA', iso3: 'CAN' },
  'chile': { capital: 'Santiago', iso2: 'CL', iso3: 'CHL' },
  'colombia': { capital: 'Bogotá', iso2: 'CO', iso3: 'COL' },
  'costa rica': { capital: 'San José', iso2: 'CR', iso3: 'CRI' },
  'cuba': { capital: 'Havana', iso2: 'CU', iso3: 'CUB' },
  'ecuador': { capital: 'Quito', iso2: 'EC', iso3: 'ECU' },
  'el salvador': { capital: 'San Salvador', iso2: 'SV', iso3: 'SLV' },
  'guatemala': { capital: 'Guatemala City', iso2: 'GT', iso3: 'GTM' },
  'haiti': { capital: 'Port-au-Prince', iso2: 'HT', iso3: 'HTI' },
  'honduras': { capital: 'Tegucigalpa', iso2: 'HN', iso3: 'HND' },
  'jamaica': { capital: 'Kingston', iso2: 'JM', iso3: 'JAM' },
  'mexico': { capital: 'Mexico City', iso2: 'MX', iso3: 'MEX' },
  'nicaragua': { capital: 'Managua', iso2: 'NI', iso3: 'NIC' },
  'panama': { capital: 'Panama City', iso2: 'PA', iso3: 'PAN' },
  'paraguay': { capital: 'Asunción', iso2: 'PY', iso3: 'PRY' },
  'peru': { capital: 'Lima', iso2: 'PE', iso3: 'PER' },
  'united states': { capital: 'Washington, D.C.', iso2: 'US', iso3: 'USA' },
  'uruguay': { capital: 'Montevideo', iso2: 'UY', iso3: 'URY' },
  'venezuela': { capital: 'Caracas', iso2: 'VE', iso3: 'VEN' },

  // Africa
  'algeria': { capital: 'Algiers', iso2: 'DZ', iso3: 'DZA' },
  'angola': { capital: 'Luanda', iso2: 'AO', iso3: 'AGO' },
  'benin': { capital: 'Porto-Novo', iso2: 'BJ', iso3: 'BEN' },
  'botswana': { capital: 'Gaborone', iso2: 'BW', iso3: 'BWA' },
  'burkina faso': { capital: 'Ouagadougou', iso2: 'BF', iso3: 'BFA' },
  'cameroon': { capital: 'Yaoundé', iso2: 'CM', iso3: 'CMR' },
  'egypt': { capital: 'Cairo', iso2: 'EG', iso3: 'EGY' },
  'ethiopia': { capital: 'Addis Ababa', iso2: 'ET', iso3: 'ETH' },
  'ghana': { capital: 'Accra', iso2: 'GH', iso3: 'GHA' },
  'kenya': { capital: 'Nairobi', iso2: 'KE', iso3: 'KEN' },
  'libya': { capital: 'Tripoli', iso2: 'LY', iso3: 'LBY' },
  'morocco': { capital: 'Rabat', iso2: 'MA', iso3: 'MAR' },
  'nigeria': { capital: 'Abuja', iso2: 'NG', iso3: 'NGA' },
  'south africa': { capital: 'Pretoria', iso2: 'ZA', iso3: 'ZAF' },
  'sudan': { capital: 'Khartoum', iso2: 'SD', iso3: 'SDN' },
  'tanzania': { capital: 'Dodoma', iso2: 'TZ', iso3: 'TZA' },
  'tunisia': { capital: 'Tunis', iso2: 'TN', iso3: 'TUN' },
  'uganda': { capital: 'Kampala', iso2: 'UG', iso3: 'UGA' },
  'zimbabwe': { capital: 'Harare', iso2: 'ZW', iso3: 'ZWE' },

  // Oceania
  'australia': { capital: 'Canberra', iso2: 'AU', iso3: 'AUS' },
  'fiji': { capital: 'Suva', iso2: 'FJ', iso3: 'FJI' },
  'new zealand': { capital: 'Wellington', iso2: 'NZ', iso3: 'NZL' },
  'papua new guinea': { capital: 'Port Moresby', iso2: 'PG', iso3: 'PNG' },
};

export function getCountryInfo(countryName: string): CountryInfo {
  const normalized = countryName.toLowerCase();
  return COUNTRY_INFO[normalized] || { 
    capital: '', 
    iso2: countryName.substring(0, 2).toUpperCase(), 
    iso3: countryName.substring(0, 3).toUpperCase() 
  };
}
